# Generated by Django 6.0 on 2025-12-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('view_admin_report', 'Can view admin report')]},
        ),
    ]
